### ISSUE TITLE
using getUserPointer

### ISSUE THREAD

**Issue by dukuo** [giniedp/ammojs-typed#1]
Hi there!
I'm trying to use getUserPointer but it seems that it's returning a static function instead of the one I set using setUserPointer like  this: 

```
const btV:any = new Ammo.btVector3(0, 0, 0);
btV.myData = {
      tag: 'woof'
}
body.setUserPointer(btV);
```

I've searched quite a bit but I still can't figure out what I'm doing wrong 

@kripken

**Comment by giniedp** [comment]
sorry but unfortunately i can not give any support on this topic. I'd suggest to raise the issue on the [original repository](https://github.com/kripken/ammo.js)
