### ISSUE TITLE
Introducing the package, an error occurred when starting the project

### ISSUE THREAD

**Issue by bihongbin3027** [giniedp/ammojs-typed#12]
![image](https://user-images.githubusercontent.com/15045200/153145247-d3d7cf17-b3d9-4c45-9f51-d8fe917f2e56.png)

**Comment by mrchantey** [comment]
These errors are harmless but we need to stop webpack from hanging when it sees them. 
Add the following to your webpack config:
```ts
resolve: {
  fallback: {
    fs: false,
    path: false
  }
}
```
