### ISSUE TITLE
Cannot create btDiscrateDynamicsWorld

### ISSUE THREAD

**Issue by Jeroenvdv1993** [giniedp/ammojs-typed#3]
Hey,

I'm trying to create a simple physics scene following this: https://stackblitz.com/edit/ammojs-typed-falling-cubes?file=simulation.ts.
(And https://github.com/kripken/ammo.js/blob/master/examples/webgl_demo/worker.js#L6)
However since the last commit btDbvtBroadphase doesn't extend btBroadPhaseInterface anymore, but the constructor of btDiscreteDynamicsWorld still expects it. What do I need to do to create a simple btDiscreteDynamicsWorld?

Greets,
Jeroen.

**Comment by giniedp** [comment]
thanks. During the update i forgot to add exactly that manual adjustment. I released version `1.0.4` to fix that.
